micronaut.application.name=demo-data

# Database Configuration
datasources.default.url=jdbc:oracle:thin:@${DB_SERVER}/${DB_SERVICENAME}
datasources.default.username=${DB_USER}
datasources.default.password=${DB_PASSWORD}

# JPA / Hibernate Configuration
jpa.default.reactive=true
jpa.default.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
jpa.default.properties.hibernate.hbm2ddl.auto=validate
jpa.default.properties.hibernate.connection.driver_class=io.vertx.oracleclient.spi.OracleDriver
jpa.default.properties.hibernate.connection.url=jdbc:oracle:thin:@${DB_SERVER}/${DB_SERVICENAME}
jpa.default.properties.hibernate.connection.username=${DB_USER}
jpa.default.properties.hibernate.connection.password=${DB_PASSWORD}
jpa.default.properties.hibernate.connection.pool_size=${DB_POOLSIZE:10}

# Flyway Configuration
flyway.datasources.default.enabled=${FLYWAY_ENABLED:true}
flyway.datasources.default.baseline-on-migrate=true
flyway.datasources.default.baseline-version=0
flyway.datasources.default.url=jdbc:oracle:thin:@${DB_SERVER}/${DB_SERVICENAME}
flyway.datasources.default.username=${DB_USER}
flyway.datasources.default.password=${DB_PASSWORD}
