-- Create authors table
CREATE TABLE authors (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    country VARCHAR(100),
    birth_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_authors_name ON authors(name);

-- Add foreign key constraint
ALTER TABLE books ADD CONSTRAINT fk_books_author_id
FOREIGN KEY (author_id) REFERENCES authors(id);


